services:
  form.type.data_analysis_query_parameter:
    class: Invit\DataAnalysisBundle\Form\Type\DataAnalysisQueryParameterType
    arguments: ['@doctrine.orm.entity_manager']
    tags:
      - { name: form.type }
